### ISSUE TITLE
Text has bad alignment on mobile

### ISSUE THREAD

**Issue by pizzamaker** [sstangl/tuja-vortaro#4]
See screenshot

**Comment by pizzamaker** [comment]
![tmp_3543-screenshot_2016-01-17-14-29-16-1358634992](https://cloud.githubusercontent.com/assets/11085215/12378523/3398f694-bd27-11e5-9f17-18834df68eb9.png)

**Comment by sstangl** [comment]
Thanks for the report! There is a mobile version of the site that should work better for phones. It places the search bar at the bottom so that it's easier to press with your thumb.

https://sstangl.github.io/tuja-vortaro/mobile

It was originally made for (and tested on) FirefoxOS, so it might work differently or not at all in other browsers. If things are broken on Android or iPhone or Windows Phone or something, please file an issue! I don't have any of those devices, so I may need your help running tests.

To fix this, we should detect "Mobile" in the user agent and switch users over to the mobile version automatically. I'll open a new issue for that.

**Comment by pizzamaker** [comment]
Oh right, forgot to mention: this was tested on Android.

**Comment by sstangl** [comment]
@pizzamaker, ĉu nun funkcias ĝi sur poŝtelefonoj por vi?

**Comment by pizzamaker** [comment]
Jes, dankon! :)
